# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dmitrychebanov/untitled002/design08plusF.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LatticeNavi(object):
    def setupUi(self, LatticeNavi):
        LatticeNavi.setObjectName("LatticeNavi")
        LatticeNavi.resize(809, 696)
        self.centralWidget = QtWidgets.QWidget(LatticeNavi)
        self.centralWidget.setObjectName("centralWidget")
        self.Navigation = QtWidgets.QGroupBox(self.centralWidget)
        self.Navigation.setGeometry(QtCore.QRect(10, 265, 791, 206))
        self.Navigation.setObjectName("Navigation")
        self.NavInputHypHint = QtWidgets.QLineEdit(self.Navigation)
        self.NavInputHypHint.setGeometry(QtCore.QRect(10, 40, 371, 21))
        self.NavInputHypHint.setObjectName("NavInputHypHint")
        self.label = QtWidgets.QLabel(self.Navigation)
        self.label.setGeometry(QtCore.QRect(10, 20, 771, 16))
        self.label.setObjectName("label")
        self.NavUp = QtWidgets.QPushButton(self.Navigation)
        self.NavUp.setGeometry(QtCore.QRect(380, 35, 86, 32))
        self.NavUp.setObjectName("NavUp")
        self.NavDown = QtWidgets.QPushButton(self.Navigation)
        self.NavDown.setGeometry(QtCore.QRect(460, 35, 86, 32))
        self.NavDown.setObjectName("NavDown")
        self.label_4 = QtWidgets.QLabel(self.Navigation)
        self.label_4.setGeometry(QtCore.QRect(270, 155, 506, 16))
        self.label_4.setObjectName("label_4")
        self.spinBox = QtWidgets.QSpinBox(self.Navigation)
        self.spinBox.setGeometry(QtCore.QRect(595, 175, 42, 22))
        self.spinBox.setMaximum(99)
        self.spinBox.setObjectName("spinBox")
        self.LowLeftOnly_3 = QtWidgets.QLineEdit(self.Navigation)
        self.LowLeftOnly_3.setGeometry(QtCore.QRect(270, 110, 246, 21))
        self.LowLeftOnly_3.setObjectName("LowLeftOnly_3")
        self.label_12 = QtWidgets.QLabel(self.Navigation)
        self.label_12.setGeometry(QtCore.QRect(530, 90, 241, 16))
        self.label_12.setObjectName("label_12")
        self.LowLeftOnly_4 = QtWidgets.QLineEdit(self.Navigation)
        self.LowLeftOnly_4.setGeometry(QtCore.QRect(530, 110, 246, 21))
        self.LowLeftOnly_4.setObjectName("LowLeftOnly_4")
        self.label_14 = QtWidgets.QLabel(self.Navigation)
        self.label_14.setGeometry(QtCore.QRect(270, 70, 521, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Navigation)
        self.label_15.setGeometry(QtCore.QRect(270, 90, 241, 16))
        self.label_15.setObjectName("label_15")
        self.CalcNeighbors = QtWidgets.QPushButton(self.Navigation)
        self.CalcNeighbors.setGeometry(QtCore.QRect(710, 170, 71, 32))
        self.CalcNeighbors.setObjectName("CalcNeighbors")
        self.label_16 = QtWidgets.QLabel(self.Navigation)
        self.label_16.setGeometry(QtCore.QRect(270, 180, 326, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.Navigation)
        self.label_17.setGeometry(QtCore.QRect(640, 180, 71, 16))
        self.label_17.setObjectName("label_17")
        self.NavNextLevel = QtWidgets.QTextBrowser(self.Navigation)
        self.NavNextLevel.setGeometry(QtCore.QRect(10, 70, 251, 126))
        self.NavNextLevel.setObjectName("NavNextLevel")
        self.To_Chosen = QtWidgets.QPushButton(self.Navigation)
        self.To_Chosen.setGeometry(QtCore.QRect(550, 35, 116, 32))
        self.To_Chosen.setObjectName("To_Chosen")
        self.Decrypt = QtWidgets.QPushButton(self.Navigation)
        self.Decrypt.setGeometry(QtCore.QRect(660, 35, 121, 32))
        self.Decrypt.setObjectName("Decrypt")
        self.DecryptBlock = QtWidgets.QGroupBox(self.centralWidget)
        self.DecryptBlock.setGeometry(QtCore.QRect(10, 525, 791, 106))
        self.DecryptBlock.setObjectName("DecryptBlock")
        self.DecryptOutput = QtWidgets.QTextBrowser(self.DecryptBlock)
        self.DecryptOutput.setGeometry(QtCore.QRect(10, 25, 251, 71))
        self.DecryptOutput.setObjectName("DecryptOutput")
        self.DecryptByNumber = QtWidgets.QLineEdit(self.DecryptBlock)
        self.DecryptByNumber.setGeometry(QtCore.QRect(270, 75, 246, 21))
        self.DecryptByNumber.setObjectName("DecryptByNumber")
        self.label_11 = QtWidgets.QLabel(self.DecryptBlock)
        self.label_11.setGeometry(QtCore.QRect(270, 55, 231, 16))
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.DecryptBlock)
        self.label_13.setGeometry(QtCore.QRect(535, 55, 246, 16))
        self.label_13.setObjectName("label_13")
        self.DecryptAll = QtWidgets.QPushButton(self.DecryptBlock)
        self.DecryptAll.setGeometry(QtCore.QRect(265, 25, 256, 32))
        self.DecryptAll.setObjectName("DecryptAll")
        self.comboBox = QtWidgets.QComboBox(self.DecryptBlock)
        self.comboBox.setGeometry(QtCore.QRect(530, 70, 246, 32))
        self.comboBox.setObjectName("comboBox")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 5, 801, 256))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.WhichBorder = QtWidgets.QGroupBox(self.tab)
        self.WhichBorder.setGeometry(QtCore.QRect(0, 0, 561, 66))
        self.WhichBorder.setObjectName("WhichBorder")
        self.uppradioButton = QtWidgets.QRadioButton(self.WhichBorder)
        self.uppradioButton.setGeometry(QtCore.QRect(20, 40, 726, 20))
        self.uppradioButton.setObjectName("uppradioButton")
        self.lowradioButton = QtWidgets.QRadioButton(self.WhichBorder)
        self.lowradioButton.setGeometry(QtCore.QRect(20, 20, 746, 20))
        self.lowradioButton.setChecked(True)
        self.lowradioButton.setObjectName("lowradioButton")
        self.LowerBorder = QtWidgets.QGroupBox(self.tab)
        self.LowerBorder.setGeometry(QtCore.QRect(0, 65, 791, 161))
        self.LowerBorder.setTitle("")
        self.LowerBorder.setObjectName("LowerBorder")
        self.label_3 = QtWidgets.QLabel(self.LowerBorder)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 91, 16))
        self.label_3.setObjectName("label_3")
        self.CalcButLower = QtWidgets.QPushButton(self.LowerBorder)
        self.CalcButLower.setGeometry(QtCore.QRect(10, 0, 114, 32))
        self.CalcButLower.setObjectName("CalcButLower")
        self.LowBord = QtWidgets.QTextBrowser(self.LowerBorder)
        self.LowBord.setGeometry(QtCore.QRect(10, 30, 251, 121))
        self.LowBord.setObjectName("LowBord")
        self.label_5 = QtWidgets.QLabel(self.LowerBorder)
        self.label_5.setGeometry(QtCore.QRect(270, 80, 241, 16))
        self.label_5.setObjectName("label_5")
        self.LowLeftOnly = QtWidgets.QLineEdit(self.LowerBorder)
        self.LowLeftOnly.setGeometry(QtCore.QRect(270, 100, 246, 21))
        self.LowLeftOnly.setObjectName("LowLeftOnly")
        self.LowBordLen = QtWidgets.QTextBrowser(self.LowerBorder)
        self.LowBordLen.setGeometry(QtCore.QRect(220, 5, 41, 21))
        self.LowBordLen.setObjectName("LowBordLen")
        self.label_7 = QtWidgets.QLabel(self.LowerBorder)
        self.label_7.setGeometry(QtCore.QRect(270, 135, 516, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.LowerBorder)
        self.label_8.setGeometry(QtCore.QRect(270, 60, 521, 16))
        self.label_8.setObjectName("label_8")
        self.LowLeftOnly_2 = QtWidgets.QLineEdit(self.LowerBorder)
        self.LowLeftOnly_2.setGeometry(QtCore.QRect(530, 100, 246, 21))
        self.LowLeftOnly_2.setObjectName("LowLeftOnly_2")
        self.label_9 = QtWidgets.QLabel(self.LowerBorder)
        self.label_9.setGeometry(QtCore.QRect(535, 80, 241, 16))
        self.label_9.setObjectName("label_9")
        self.radioButtonSortOrb = QtWidgets.QRadioButton(self.LowerBorder)
        self.radioButtonSortOrb.setGeometry(QtCore.QRect(270, 5, 506, 20))
        self.radioButtonSortOrb.setChecked(True)
        self.radioButtonSortOrb.setObjectName("radioButtonSortOrb")
        self.radioButtonSortLen = QtWidgets.QRadioButton(self.LowerBorder)
        self.radioButtonSortLen.setGeometry(QtCore.QRect(270, 25, 531, 20))
        self.radioButtonSortLen.setObjectName("radioButtonSortLen")
        self.Sign = QtWidgets.QGroupBox(self.tab)
        self.Sign.setGeometry(QtCore.QRect(590, 0, 201, 66))
        self.Sign.setObjectName("Sign")
        self.Radiobutton_minus = QtWidgets.QRadioButton(self.Sign)
        self.Radiobutton_minus.setGeometry(QtCore.QRect(20, 40, 726, 20))
        self.Radiobutton_minus.setObjectName("Radiobutton_minus")
        self.Radiobutton_plus = QtWidgets.QRadioButton(self.Sign)
        self.Radiobutton_plus.setGeometry(QtCore.QRect(20, 20, 746, 20))
        self.Radiobutton_plus.setChecked(True)
        self.Radiobutton_plus.setObjectName("Radiobutton_plus")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.LowerBorder_2 = QtWidgets.QGroupBox(self.tab_2)
        self.LowerBorder_2.setGeometry(QtCore.QRect(0, 0, 791, 226))
        self.LowerBorder_2.setObjectName("LowerBorder_2")
        self.label_6 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_6.setGeometry(QtCore.QRect(415, 95, 91, 16))
        self.label_6.setObjectName("label_6")
        self.DisplayFilter = QtWidgets.QTextBrowser(self.LowerBorder_2)
        self.DisplayFilter.setGeometry(QtCore.QRect(535, 65, 251, 151))
        self.DisplayFilter.setObjectName("DisplayFilter")
        self.label_10 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_10.setGeometry(QtCore.QRect(5, 80, 241, 16))
        self.label_10.setObjectName("label_10")
        self.FiltLeftOnly = QtWidgets.QLineEdit(self.LowerBorder_2)
        self.FiltLeftOnly.setGeometry(QtCore.QRect(5, 100, 246, 21))
        self.FiltLeftOnly.setObjectName("FiltLeftOnly")
        self.LeftNumberFilters = QtWidgets.QTextBrowser(self.LowerBorder_2)
        self.LeftNumberFilters.setGeometry(QtCore.QRect(480, 90, 51, 21))
        self.LeftNumberFilters.setObjectName("LeftNumberFilters")
        self.label_18 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_18.setGeometry(QtCore.QRect(10, 175, 121, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_19.setGeometry(QtCore.QRect(5, 60, 306, 16))
        self.label_19.setObjectName("label_19")
        self.FiltLeftNot = QtWidgets.QLineEdit(self.LowerBorder_2)
        self.FiltLeftNot.setGeometry(QtCore.QRect(5, 145, 246, 21))
        self.FiltLeftNot.setObjectName("FiltLeftNot")
        self.label_20 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_20.setGeometry(QtCore.QRect(10, 125, 241, 16))
        self.label_20.setObjectName("label_20")
        self.radioButtonMore = QtWidgets.QRadioButton(self.LowerBorder_2)
        self.radioButtonMore.setGeometry(QtCore.QRect(130, 175, 101, 20))
        self.radioButtonMore.setChecked(True)
        self.radioButtonMore.setObjectName("radioButtonMore")
        self.radioButtonLess = QtWidgets.QRadioButton(self.LowerBorder_2)
        self.radioButtonLess.setGeometry(QtCore.QRect(215, 175, 101, 20))
        self.radioButtonLess.setObjectName("radioButtonLess")
        self.radioButtonEqual = QtWidgets.QRadioButton(self.LowerBorder_2)
        self.radioButtonEqual.setGeometry(QtCore.QRect(305, 175, 101, 20))
        self.radioButtonEqual.setChecked(False)
        self.radioButtonEqual.setObjectName("radioButtonEqual")
        self.label_21 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_21.setGeometry(QtCore.QRect(10, 205, 200, 16))
        self.label_21.setObjectName("label_21")
        self.ParentsFilter = QtWidgets.QTextBrowser(self.LowerBorder_2)
        self.ParentsFilter.setGeometry(QtCore.QRect(210, 200, 55, 21))
        self.ParentsFilter.setObjectName("ParentsFilter")
        self.groupBox = QtWidgets.QGroupBox(self.LowerBorder_2)
        self.groupBox.setGeometry(QtCore.QRect(315, 55, 211, 31))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButtonPlus = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonPlus.setGeometry(QtCore.QRect(80, 5, 126, 20))
        self.radioButtonPlus.setObjectName("radioButtonPlus")
        self.radioButtonMinus = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonMinus.setGeometry(QtCore.QRect(145, 5, 66, 20))
        self.radioButtonMinus.setObjectName("radioButtonMinus")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 5, 66, 16))
        self.label_22.setObjectName("label_22")
        self.MinusHypsTotal = QtWidgets.QTextBrowser(self.LowerBorder_2)
        self.MinusHypsTotal.setGeometry(QtCore.QRect(510, 30, 71, 21))
        self.MinusHypsTotal.setObjectName("MinusHypsTotal")
        self.checkBox = QtWidgets.QCheckBox(self.LowerBorder_2)
        self.checkBox.setGeometry(QtCore.QRect(10, 20, 87, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.label_23 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_23.setGeometry(QtCore.QRect(205, 30, 116, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_24.setGeometry(QtCore.QRect(395, 30, 116, 16))
        self.label_24.setObjectName("label_24")
        self.checkBox_2 = QtWidgets.QCheckBox(self.LowerBorder_2)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 35, 87, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.CalcButAll = QtWidgets.QPushButton(self.LowerBorder_2)
        self.CalcButAll.setGeometry(QtCore.QRect(80, 25, 114, 32))
        self.CalcButAll.setObjectName("CalcButAll")
        self.PlusHypsTotal = QtWidgets.QTextBrowser(self.LowerBorder_2)
        self.PlusHypsTotal.setGeometry(QtCore.QRect(310, 30, 71, 21))
        self.PlusHypsTotal.setObjectName("PlusHypsTotal")
        self.Show = QtWidgets.QPushButton(self.LowerBorder_2)
        self.Show.setGeometry(QtCore.QRect(410, 110, 126, 32))
        self.Show.setObjectName("Show")
        self.Load = QtWidgets.QPushButton(self.LowerBorder_2)
        self.Load.setGeometry(QtCore.QRect(670, 25, 114, 32))
        self.Load.setObjectName("Load")
        self.LenHypsFilter = QtWidgets.QSpinBox(self.LowerBorder_2)
        self.LenHypsFilter.setGeometry(QtCore.QRect(370, 175, 42, 22))
        self.LenHypsFilter.setMaximum(99)
        self.LenHypsFilter.setObjectName("LenHypsFilter")
        self.label_25 = QtWidgets.QLabel(self.LowerBorder_2)
        self.label_25.setGeometry(QtCore.QRect(595, 20, 86, 41))
        self.label_25.setObjectName("label_25")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.CalcButAll_2 = QtWidgets.QPushButton(self.tab_4)
        self.CalcButAll_2.setGeometry(QtCore.QRect(15, 15, 114, 32))
        self.CalcButAll_2.setObjectName("CalcButAll_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_3.setGeometry(QtCore.QRect(175, 55, 141, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_4.setGeometry(QtCore.QRect(175, 40, 87, 20))
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_5.setGeometry(QtCore.QRect(175, 70, 141, 20))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_6.setGeometry(QtCore.QRect(175, 85, 131, 20))
        self.checkBox_6.setObjectName("checkBox_6")
        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(130, 15, 41, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(170, 15, 41, 16))
        self.label_27.setObjectName("label_27")
        self.LowLeftOnly_5 = QtWidgets.QLineEdit(self.tab_4)
        self.LowLeftOnly_5.setGeometry(QtCore.QRect(40, 110, 246, 21))
        self.LowLeftOnly_5.setObjectName("LowLeftOnly_5")
        self.WhichBorder_2 = QtWidgets.QGroupBox(self.tab_4)
        self.WhichBorder_2.setGeometry(QtCore.QRect(5, 160, 791, 66))
        self.WhichBorder_2.setObjectName("WhichBorder_2")
        self.uppradioButton_2 = QtWidgets.QRadioButton(self.WhichBorder_2)
        self.uppradioButton_2.setGeometry(QtCore.QRect(20, 40, 726, 20))
        self.uppradioButton_2.setObjectName("uppradioButton_2")
        self.lowradioButton_2 = QtWidgets.QRadioButton(self.WhichBorder_2)
        self.lowradioButton_2.setGeometry(QtCore.QRect(20, 20, 746, 20))
        self.lowradioButton_2.setChecked(True)
        self.lowradioButton_2.setObjectName("lowradioButton_2")
        self.NavNextLevel_2 = QtWidgets.QTextBrowser(self.tab_4)
        self.NavNextLevel_2.setGeometry(QtCore.QRect(510, 20, 251, 126))
        self.NavNextLevel_2.setObjectName("NavNextLevel_2")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.DecryptOutput_2 = QtWidgets.QTextBrowser(self.tab_3)
        self.DecryptOutput_2.setGeometry(QtCore.QRect(495, 15, 251, 126))
        self.DecryptOutput_2.setObjectName("DecryptOutput_2")
        self.Calc_Predict = QtWidgets.QPushButton(self.tab_3)
        self.Calc_Predict.setGeometry(QtCore.QRect(10, 10, 206, 32))
        self.Calc_Predict.setObjectName("Calc_Predict")
        self.tabWidget.addTab(self.tab_3, "")
        self.Chosen_Ones = QtWidgets.QTextBrowser(self.centralWidget)
        self.Chosen_Ones.setGeometry(QtCore.QRect(545, 470, 251, 71))
        self.Chosen_Ones.setObjectName("Chosen_Ones")
        self.For_Chosen_Input = QtWidgets.QLineEdit(self.centralWidget)
        self.For_Chosen_Input.setGeometry(QtCore.QRect(295, 490, 246, 21))
        self.For_Chosen_Input.setObjectName("For_Chosen_Input")
        self.Chosen_add = QtWidgets.QPushButton(self.centralWidget)
        self.Chosen_add.setGeometry(QtCore.QRect(375, 510, 86, 32))
        self.Chosen_add.setObjectName("Chosen_add")
        self.Chosen_del = QtWidgets.QPushButton(self.centralWidget)
        self.Chosen_del.setGeometry(QtCore.QRect(455, 510, 86, 32))
        self.Chosen_del.setObjectName("Chosen_del")
        self.label_28 = QtWidgets.QLabel(self.centralWidget)
        self.label_28.setGeometry(QtCore.QRect(20, 470, 506, 16))
        self.label_28.setObjectName("label_28")
        LatticeNavi.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(LatticeNavi)
        self.mainToolBar.setObjectName("mainToolBar")
        LatticeNavi.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(LatticeNavi)
        self.statusBar.setObjectName("statusBar")
        LatticeNavi.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(LatticeNavi)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menuBar.setObjectName("menuBar")
        LatticeNavi.setMenuBar(self.menuBar)
        self.action_3 = QtWidgets.QAction(LatticeNavi)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(LatticeNavi)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LatticeNavi)

    def retranslateUi(self, LatticeNavi):
        _translate = QtCore.QCoreApplication.translate
        LatticeNavi.setWindowTitle(_translate("LatticeNavi", "MainWindow"))
        self.Navigation.setTitle(_translate("LatticeNavi", "Навигация - поиск гипотез с меньшим либо большим числом признаков, отталкиваясь от введенного набора признаков"))
        self.label.setText(_translate("LatticeNavi", "Введите гипотезу, и найдите связанные гипотезы. Либо введите интересующий набор признаков, и узнайте его статус:"))
        self.NavUp.setText(_translate("LatticeNavi", "Длиннее"))
        self.NavDown.setText(_translate("LatticeNavi", "Короче"))
        self.label_4.setText(_translate("LatticeNavi", "Мы искали введенный Вами набор признаков целиком. Попробуйте снизить "))
        self.label_12.setText(_translate("LatticeNavi", "Убрать содержащие эти признаки:"))
        self.label_14.setText(_translate("LatticeNavi", "Слишком много результатов? Примените фильтры, введя признаки через \',\' :"))
        self.label_15.setText(_translate("LatticeNavi", " Оставить содержащие эти признаки:"))
        self.CalcNeighbors.setText(_translate("LatticeNavi", "Искать"))
        self.label_16.setText(_translate("LatticeNavi", " порог поиска: совпадение может быть меньше на"))
        self.label_17.setText(_translate("LatticeNavi", "признаков"))
        self.To_Chosen.setText(_translate("LatticeNavi", "В Избранное"))
        self.Decrypt.setText(_translate("LatticeNavi", "Расшифровать"))
        self.DecryptBlock.setTitle(_translate("LatticeNavi", "Расшифровка номеров признаков "))
        self.label_11.setText(_translate("LatticeNavi", "Номер признака или вся гипотеза:"))
        self.label_13.setText(_translate("LatticeNavi", "Выбрать признак и узнать его номер:"))
        self.DecryptAll.setText(_translate("LatticeNavi", "Вывести все признаки и их номера"))
        self.WhichBorder.setTitle(_translate("LatticeNavi", "Вычисление начальных наборов гипотез. Выберите тип гипотез, которые планируется вычислить:"))
        self.uppradioButton.setText(_translate("LatticeNavi", "признаков - максимум, но подтверждающих примеров - минимум"))
        self.lowradioButton.setText(_translate("LatticeNavi", "подтверждающих примеров - максимум, но признаков - минимум"))
        self.label_3.setText(_translate("LatticeNavi", "Всего в окне:"))
        self.CalcButLower.setText(_translate("LatticeNavi", "Вычислить"))
        self.label_5.setText(_translate("LatticeNavi", " Оставить содержащие эти признаки:"))
        self.label_7.setText(_translate("LatticeNavi", "Вы можете скопировать любую гипотезу и вставить в окно в блоке \"Навигация\""))
        self.label_8.setText(_translate("LatticeNavi", "Слишком много результатов? Примените фильтры, введя признаки через \',\' :"))
        self.label_9.setText(_translate("LatticeNavi", "Убрать содержащие эти признаки:"))
        self.radioButtonSortOrb.setText(_translate("LatticeNavi", "сортировать по количеству примеров-родителей (сначала - наибольшие)"))
        self.radioButtonSortLen.setText(_translate("LatticeNavi", "сортировать по количеству признаков в гипотезе (сначала - короткие)"))
        self.Sign.setTitle(_translate("LatticeNavi", "Знак примеров:"))
        self.Radiobutton_minus.setText(_translate("LatticeNavi", "минус"))
        self.Radiobutton_plus.setText(_translate("LatticeNavi", "плюс"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LatticeNavi", "Цепочки"))
        self.LowerBorder_2.setTitle(_translate("LatticeNavi", "Вычисление всех возможных гипотез на обучающей выборке"))
        self.label_6.setText(_translate("LatticeNavi", "Остается:"))
        self.label_10.setText(_translate("LatticeNavi", "Должны содержать эти признаки:"))
        self.label_18.setText(_translate("LatticeNavi", "Число признаков: "))
        self.label_19.setText(_translate("LatticeNavi", "Примените фильтры, введя признаки через \',\' :"))
        self.label_20.setText(_translate("LatticeNavi", "Не должны содержать эти признаки:"))
        self.radioButtonMore.setText(_translate("LatticeNavi", "больше"))
        self.radioButtonLess.setText(_translate("LatticeNavi", "меньше"))
        self.radioButtonEqual.setText(_translate("LatticeNavi", "равно"))
        self.label_21.setText(_translate("LatticeNavi", "Число родителей, не меньше: "))
        self.radioButtonPlus.setText(_translate("LatticeNavi", "Плюс"))
        self.radioButtonMinus.setText(_translate("LatticeNavi", "Минус"))
        self.label_22.setText(_translate("LatticeNavi", "Гипотезы:"))
        self.checkBox.setText(_translate("LatticeNavi", "Плюс"))
        self.label_23.setText(_translate("LatticeNavi", "Плюс-гипотезы:"))
        self.label_24.setText(_translate("LatticeNavi", "Минус-гипотезы:"))
        self.checkBox_2.setText(_translate("LatticeNavi", "Минус"))
        self.CalcButAll.setText(_translate("LatticeNavi", "Вычислить"))
        self.Show.setText(_translate("LatticeNavi", "Вывести"))
        self.Load.setText(_translate("LatticeNavi", "Загрузить"))
        self.label_25.setText(_translate("LatticeNavi", "Уже ранее \n"
"вычислены? "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LatticeNavi", "Все гипотезы"))
        self.CalcButAll_2.setText(_translate("LatticeNavi", "Вычислить"))
        self.checkBox_3.setText(_translate("LatticeNavi", "Сходство с ЗКП"))
        self.checkBox_4.setText(_translate("LatticeNavi", "Сходство"))
        self.checkBox_5.setText(_translate("LatticeNavi", "Различие"))
        self.checkBox_6.setText(_translate("LatticeNavi", "Различие с ЗКП"))
        self.label_26.setText(_translate("LatticeNavi", "Плюс"))
        self.label_27.setText(_translate("LatticeNavi", "Минус"))
        self.WhichBorder_2.setTitle(_translate("LatticeNavi", "Вычисление начальных наборов гипотез. Выберите тип гипотез, которые планируется вычислить:"))
        self.uppradioButton_2.setText(_translate("LatticeNavi", "c наибольшим числом признаков, но с наименьшим количеством подтверждающих примеров (\"родителей\")"))
        self.lowradioButton_2.setText(_translate("LatticeNavi", "с наибольшим количеством подтверждающих примеров (\"родителей\"), но с наименьшим числом признаков"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("LatticeNavi", "Закономерности"))
        self.Calc_Predict.setText(_translate("LatticeNavi", "Вычислить предсказания"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LatticeNavi", "Предсказания"))
        self.Chosen_add.setText(_translate("LatticeNavi", "Добавить"))
        self.Chosen_del.setText(_translate("LatticeNavi", "Удалить"))
        self.label_28.setText(_translate("LatticeNavi", "Избранное: не теряйте интересные гипотезы! Складывайте их здесь"))
        self.action_3.setText(_translate("LatticeNavi", "полные"))

